export const MONTHLY_ACCOUNTABILITY_PRODUCT_ID = "prod_QVPvR9dIlsGDr9";
export const WEEKLY_ACCOUNTABILITY_PRODUCT_ID = "prod_QVPpvFpBmnQ97g";
export const TEST_MODE_DAILY_ACCOUNTABILITY_PRODUCT_ID = "prod_QSTWXLF2x2W86n";
export const TESTING_LIVE_DAILY_CHARGE_PRODUCT_ID = "prod_QZES5wLjvB3iYH";
export const TEST_MODE_4_SESSION = "prod_QbpN5CHqhtRztl";
export const TEST_MODE_12_SESSION_LITE = "prod_Qc58Zf5hDiB2pL";
export const TEST_MODE_12_SESSION = "prod_Qc597imtA9qcBq";
export const STRIPE_SUBSCRIPTION_PRODUCT_IDS = [
  MONTHLY_ACCOUNTABILITY_PRODUCT_ID,
  WEEKLY_ACCOUNTABILITY_PRODUCT_ID,
  TEST_MODE_DAILY_ACCOUNTABILITY_PRODUCT_ID,
  TESTING_LIVE_DAILY_CHARGE_PRODUCT_ID,
  TEST_MODE_4_SESSION,
  TEST_MODE_12_SESSION_LITE,
  TEST_MODE_12_SESSION,
];
